// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qryhswwuvpisvezpeksw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyeWhzd3d1dnBpc3ZlenBla3N3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MTMzMDAsImV4cCI6MjA1MzI4OTMwMH0.G_Wn9uY9D92pV9YMsF_piB0inXhtGmY27NYHkOh8r1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);